### ISSUE TITLE
Invitable with an API

### ISSUE THREAD

**Issue by adampetrie** [the-refinery/invitational#22]
Hi,

I have a rails app that is an API only. I am wondering if Invitable would work well in this scenario as I would need to create invites for entities that live outside of the rails app.

For example, if I try to create an invitation in a controller and pass an `invitable` type such as 'project' that does not represent a model in my app, the call errors out.

Am I maybe barking up the wrong tree by trying to use Invitable for my purposes?

Thanks.

**Comment by dgoerlich** [comment]
Fundamentally, Invitable is dependent upon the "target" entity being a model within the system.  I'm not sure how you'd implement something where the thing to which you are setting permissions isn't actually defined inside your rails app.  You will need an instance of that "target" so you can check for invitations against it specifically.

Perhaps a solution would be to build some representation model inside your app, to which the invitations are associated, which themselves define the other external entities?
